services:
  app:
    build: .
    container_name: recettes-app
    restart: always
    volumes:
      - ./data:/data
    env_file:
      - .env
    expose:
      - "8000"
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
    name: proxy-net