# Redirection HTTP -> HTTPS
server {
    listen 80;
    server_name recettes.rhassana.net;

    # Nécessaire pour le renouvellement Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# HTTPS
server {
    listen 443 ssl;
    server_name recettes.rhassana.net;

    ssl_certificate /etc/letsencrypt/live/recettes.rhassana.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/recettes.rhassana.net/privkey.pem;

    # Recommandations de sécurité SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location / {
        proxy_pass http://app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}